### PR TITLE
AWS deployment via `make deploy`

### PR DESCRIPTION
**Pull request by mattbilik**
#### What's this PR do?
Allows deployment to AWS via `make deploy`

#### Have you done the following, if applicable:

* [ ] Performed a self-review of the code?
* [ ] Linted code for good style and standards?
* [ ] Added unit tests?
* [ ] Tested manually on mobile?
* [ ] Checked for performance implications?
* [ ] Checked accessibility?
* [ ] Checked for vulnerabilities with `yarn audit --level=high`?
* [ ] Updated any documentation

### CODE REVIEW

**Comment by erxclau** [comment]
Hmm... I'll test this out but I think I want this to be in `sink` with [`@aws-sdk/client-s3`](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/getting-started-nodejs.html).

It could also be in `sink` as the bash script you have but I imagine the JavaScript SDK will be smaller than the CLI.

My main reason for wanting it in `sink` is that we could have cases where we need to deploy a graphic to S3 (i.e. our primary graphics).

**Comment by erxclau** [comment]
Ok, I have yet to run this because I'm actually not sure what it's going to do. I have my AWS keys set up in `~/.aws/credentials`, and I have non-Daily credentials in there as defaults. I _feel_ like the CLI probably has an option to specify which credential profile to use.

Also, it looks like this just deploys to a single bucket, which is a good idea for standalone subdomains. But, for things like <https://specials.michigandaily.com> or <https://magnify.michigandaily.com>, we probably also want the ability to deploy to a specific route (or key as AWS calls them).

**Comment by erxclau** [comment]
Also, not everyone has a Mac so we can't use `brew` for given. Probably another reason to move this into `sink` through the AWS S3 JavaScript SDK.

**Comment by mattbilik** [comment]
Right – this would work for subroutes (as long as a user specifies that route), but agreed that the SDK works best. I still do think that we should use the AWS CLI in the meantime since it streamlines content upload, and we can add it to existing documentation. Closing this request.

**Pull request closed without merging**
